[aws]
symbol = "  "

[conda]
symbol = " "

[dart]
format = "via [$symbol]($style)"
symbol = " "

[directory]
read_only = " "
truncation_length = 1

[docker_context]
symbol = " "

[elixir]
format = 'via [$symbol]($style)'
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
format = 'via [$symbol]($style)'
symbol = " "

[hg_branch]
symbol = " "

[java]
format = 'via [$symbol]($style)'
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
format = 'via [$symbol]($style)'
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
format = 'via [$symbol]($style)'
symbol = " "

[ruby]
symbol = " "

[rust]
format = 'via [$symbol]($style)'

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
format = 'via [$symbol]($style)'
symbol = "ﯣ "

[git_status]
disabled = true

scan_timeout = 1000
